"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.ELEMENT_WEATHER_TEMPERATURE = exports.ELEMENT_WEATHER_DESCRIPTION = exports.ELEMENT_WEATHER_CITY = exports.ELEMENT_WEATHER_BOX = exports.ELEMENT_LOADING_TEXT = exports.ELEMENT_SEARCHED_CITY = exports.ELEMENT_SEARCH_BUTTON = void 0;
const ELEMENT_SEARCH_BUTTON = document.querySelector('button');
exports.ELEMENT_SEARCH_BUTTON = ELEMENT_SEARCH_BUTTON;
const ELEMENT_SEARCHED_CITY = document.querySelector('#city');
exports.ELEMENT_SEARCHED_CITY = ELEMENT_SEARCHED_CITY;
const ELEMENT_LOADING_TEXT = document.querySelector('#load');
exports.ELEMENT_LOADING_TEXT = ELEMENT_LOADING_TEXT;
const ELEMENT_WEATHER_BOX = document.querySelector('#weather');
exports.ELEMENT_WEATHER_BOX = ELEMENT_WEATHER_BOX;
const ELEMENT_WEATHER_CITY = ELEMENT_WEATHER_BOX.firstElementChild;
exports.ELEMENT_WEATHER_CITY = ELEMENT_WEATHER_CITY;
const ELEMENT_WEATHER_DESCRIPTION = document.querySelector('#weatherDescription');
exports.ELEMENT_WEATHER_DESCRIPTION = ELEMENT_WEATHER_DESCRIPTION;
const ELEMENT_WEATHER_TEMPERATURE = ELEMENT_WEATHER_BOX.lastElementChild;
exports.ELEMENT_WEATHER_TEMPERATURE = ELEMENT_WEATHER_TEMPERATURE;